USERDIR := $(TOP)$(notdir $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST)))))/
USERINC := $(shell find $(USERDIR)$(INCDIR) -type d)
USERSRC := $(USERDIR)$(SRCDIR)
USERASM := $(USERDIR)$(ASMDIR)
USERCFILES := $(wildcard $(USERSRC)*.c)
USERASMFILES := $(wildcard $(USERASM)*.S)
USER_COFILES := $(USERCFILES:%.c=%.c.o)
USER_SOFILES := $(USERASMFILES:%.S=%.S.o)

#Debug part
USERDEBUGDIR := $(USERDIR)$(DEBUG_OBJECTS_DIR)
USERDOFILES := $(patsubst $(USERDIR)$(SRCDIR)%,$(USERDEBUGDIR)%,$(USER_COFILES))
USERDOFILES += $(patsubst $(USERDIR)$(ASMDIR)%,$(USERDEBUGDIR)%,$(USER_SOFILES))
DOFILES += $(USERDOFILES)
ALLOFILES += $(USERDOFILES)

#Release part
USERRELEASEDIR := $(USERDIR)$(RELEASE_OBJECTS_DIR)
USERROFILES := $(patsubst $(USERDIR)$(SRCDIR)%,$(USERRELEASEDIR)%,$(USER_COFILES))
USERROFILES += $(patsubst $(USERDIR)$(ASMDIR)%,$(USERRELEASEDIR)%,$(USER_SOFILES))
OFILES += $(USERROFILES)
ALLOFILES += $(USERROFILES)

#Make sure the output paths are created
OBJECTDIRS += $(USERDEBUGDIR) $(USERRELEASEDIR)

$(USERDEBUGDIR)%.c.o: $(USERSRC)%.c
	$(CC) $(CFLAGS) -I$(USERINC) -c $< -o $@

$(USERRELEASEDIR)%.c.o: $(USERSRC)%.c
	$(CC) $(CFLAGS) -I$(USERINC) -c $< -o $@

$(USERDEBUGDIR)%.S.o: $(USERASM)%.S
	$(ASMRECEIPE)

$(USERRELEASEDIR)%.S.o: $(USERASM)%.S
	$(ASMRECEIPE)
