KERNELDIR := $(TOP)$(notdir $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST)))))/
INCDIRS += $(shell find $(KERNELDIR)$(INCDIR) -type d)
KERNELSRC := $(KERNELDIR)$(SRCDIR)
KERNELCFILES := $(wildcard $(KERNELSRC)*.c)
KERNEL_OFILES := $(KERNELCFILES:%.c=%.o)

#Debug part
KERNELDEBUGDIR := $(KERNELDIR)$(DEBUG_OBJECTS_DIR)
KERNELDOFILES := $(patsubst $(KERNELDIR)$(SRCDIR)%,$(KERNELDEBUGDIR)%,$(KERNEL_OFILES))
DOFILES += $(KERNELDOFILES)

#Release part
KERNELRELEASEDIR := $(KERNELDIR)$(RELEASE_OBJECTS_DIR)
KERNELROFILES := $(patsubst $(KERNELDIR)$(SRCDIR)%,$(KERNELRELEASEDIR)%,$(KERNEL_OFILES))
OFILES += $(KERNELROFILES)

#Make sure the output paths are created
OBJECTDIRS += $(KERNELDEBUGDIR) $(KERNELRELEASEDIR)

$(KERNELDEBUGDIR)%.o $(KERNELRELEASEDIR)%.o: $(KERNELSRC)%.c
	$(CC) $(CFLAGS) -c $< -o $@

