ASSEMBLYDIR := $(TOP)$(notdir $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST)))))/
INCDIRS += $(shell find $(ASSEMBLYDIR)$(INCDIR) -type d)
ASSEMBLYASM := $(ASSEMBLYDIR)thumb2/
ASSEMBLYASMFILES := $(wildcard $(ASSEMBLYASM)*.S)
ASSEMBLYOFILES := $(ASSEMBLYASMFILES:%.S=%.o)

#Release part
ASSEMBLYRELEASEDIR := $(ASSEMBLYDIR)$(RELEASE_OBJECTS_DIR)
ASSEMBLYRELEASEOFILES := $(patsubst $(ASSEMBLYASM)%, $(ASSEMBLYRELEASEDIR)%, $(ASSEMBLYOFILES))
OFILES += $(ASSEMBLYRELEASEOFILES)
DOFILES += $(ASSEMBLYRELEASEOFILES)

OBJECTDIRS += $(ASSEMBLYDEBUGDIR) $(ASSEMBLYRELEASEDIR)

$(ASSEMBLYRELEASEDIR)%.o : $(ASSEMBLYASM)%.S
	$(ASMRECEIPE)
