ASSEMBLYDIR := $(TOP)$(notdir $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST)))))/
INCDIRS += $(shell find $(ASSEMBLYDIR)$(INCDIR) -type d)
ASSEMBLYASM := $(ASSEMBLYDIR)thumb2/
ASSEMBLYASMFILES := $(wildcard $(ASSEMBLYASM)*.S)
ASSEMBLYOFILES := $(ASSEMBLYASMFILES:%.S=%.o)

#Debug part
ASSEMBLYDEBUGDIR := $(ASSEMBLYDIR)$(DEBUG_OBJECTS_DIR)
ASSEMBLYDEBUGOFILES := $(patsubst $(ASSEMBLYASM)%, $(ASSEMBLYDEBUGDIR)%, $(ASSEMBLYOFILES))
DOFILES += $(ASSEMBLYDEBUGOFILES)

#Release part
ASSEMBLYRELEASEDIR := $(ASSEMBLYDIR)$(RELEASE_OBJECTS_DIR)
ASSEMBLYRELEASEOFILES := $(patsubst $(ASSEMBLYASM)%, $(ASSEMBLYRELEASEDIR)%, $(ASSEMBLYOFILES))
OFILES += $(ASSEMBLYRELEASEOFILES)

OBJECTDIRS += $(ASSEMBLYDEBUGDIR) $(ASSEMBLYRELEASEDIR)

$(ASSEMBLYDEBUGOFILES) $(ASSEMBLYRELEASEOFILES) : $(ASSEMBLYASMFILES)
	$(ASMRECEIPE)
