VALIDATIONDIR := $(TOP)$(notdir $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST)))))/
INCDIRS += $(shell find $(VALIDATIONDIR)$(INCDIR) -type d)
VALIDATIONSRC := $(VALIDATIONDIR)$(SRCDIR)
VALIDATIONCFILES := $(wildcard $(VALIDATIONSRC)*.c)
VALIDATION_OFILES := $(VALIDATIONCFILES:%.c=%.o)

#Debug part
VALIDATIONDEBUGDIR := $(VALIDATIONDIR)$(DEBUG_OBJECTS_DIR)
VALIDATIONDOFILES := $(patsubst $(VALIDATIONDIR)$(SRCDIR)%,$(VALIDATIONDEBUGDIR)%,$(VALIDATION_OFILES))
DOFILES += $(VALIDATIONDOFILES)

#Release part
VALIDATIONRELEASEDIR := $(VALIDATIONDIR)$(RELEASE_OBJECTS_DIR)
VALIDATIONROFILES := $(patsubst $(VALIDATIONDIR)$(SRCDIR)%,$(VALIDATIONRELEASEDIR)%,$(VALIDATION_OFILES))
OFILES += $(VALIDATIONROFILES)

#Make sure the output paths are created
OBJECTDIRS += $(VALIDATIONDEBUGDIR) $(VALIDATIONRELEASEDIR)

$(VALIDATIONDEBUGDIR)%.o $(VALIDATIONRELEASEDIR)%.o: $(VALIDATIONSRC)%.c
	$(CC) $(CFLAGS) -c $< -o $@
