COREDIR := $(TOP)$(notdir $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST)))))/
COREINC := $(shell find $(COREDIR)$(INCDIR) -type d)
CORESRC := $(COREDIR)$(SRCDIR)
COREASM := $(COREDIR)$(ASMDIR)
CORECFILES := $(wildcard $(CORESRC)*.c)
COREASMFILES := $(wildcard $(COREASM)*.S)
CORE_COFILES := $(CORECFILES:%.c=%.c.o)
CORE_SOFILES := $(COREASMFILES:%.S=%.S.o)

#Debug part
COREDEBUGDIR := $(COREDIR)$(DEBUG_OBJECTS_DIR)
COREDOFILES := $(patsubst $(COREDIR)$(SRCDIR)%,$(COREDEBUGDIR)%,$(CORE_COFILES))
COREDOFILES += $(patsubst $(COREDIR)$(ASMDIR)%,$(COREDEBUGDIR)%,$(CORE_SOFILES))
ALLOFILES += $(COREDOFILES)

#Release part
CORERELEASEDIR := $(COREDIR)$(RELEASE_OBJECTS_DIR)
COREROFILES := $(patsubst $(COREDIR)$(SRCDIR)%,$(CORERELEASEDIR)%,$(CORE_COFILES))
COREROFILES += $(patsubst $(COREDIR)$(ASMDIR)%,$(CORERELEASEDIR)%,$(CORE_SOFILES))
ALLOFILES += $(COREROFILES)

#Make sure the output paths are created
OBJECTDIRS += $(COREDEBUGDIR) $(CORERELEASEDIR)

$(COREDEBUGDIR)%.c.o $(CORERELEASEDIR)%.c.o: $(CORESRC)%.c
	$(CC) $(CFLAGS) -I$(COREINC) -c $< -o $@

$(COREDEBUGDIR)%.S.o $(CORERELEASEDIR)%.S.o: $(COREASM)%.S
	$(ASMRECEIPE)
